name: 'Hello World'
description: 'Greet someone'
inputs:
  platform:
    description: 'Target platform'
    required: true
    default: 'all'
  args:
    description: 'Arguments to be passed to the test command'
    required: false
runs:
  using: "composite"
  steps:
    - run: cargo run --release --manifest-path=${{ github.action_path }}/Cargo.toml -- ${{ inputs.platform }} -- ${{ inputs.args }}
      shell: bash