name: 'Hello World'
description: 'Greet someone'
inputs:
  platform:  # id of input
    description: 'Target platform'
    required: true
    default: 'all'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: cargo run --release --manifest-path=${{ github.action_path }} -- ${{ inputs.platform }}
      shell: bash